# Alex Felipe Barbosa

## Data Science Academy

### Fundamentos da Linguagem Python para Analise de Dados e Data Science

### Capitulo 9 - Matematica e Manipulação de Matrizes com Numpy

#### 13/03/2024

In [ ]:
# Versão da Linguagem Python
from platform import python_version
print("Versão da Linguagem Python usada neste Jupyter Notebook: ", python_version())

# Numpy

https://numpý.org

In [2]:
# Importando o Numpy
import numpy as dsa

In [3]:
dsa.__version__

'1.26.4'

In [ ]:
# Instrução para instalar a versão exata do pacote em Python
# !pip install numpy==1.22.2

# Criando Arrays Numpy

In [4]:
# Array criado a partir de uma lista Python
arr1 = dsa.array([10, 21, 32, 43, 48, 15, 76, 57, 89])

In [5]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [6]:
# Um objeto do tipo ndarray é um recipiente multidimensional de itens do mesmo tipo e tamanho
type(arr1)

numpy.ndarray

In [7]:
# Verificando o formado do array
arr1.shape

(9,)

# Indexação em Arrays Numpy

In [8]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [9]:
# Imprimindo um elemento especifico no array
arr1[4]

48

In [10]:
# Indexação
arr1[1:4]

array([21, 32, 43])

In [11]:
# Indexação 
arr1[1:4+1]

array([21, 32, 43, 48])

In [12]:
# Cria uma lista de indices
indices = [1, 2, 5, 6]

In [13]:
# Imprimindo os elementos dos indices
arr1[indices]

array([21, 32, 15, 76])

In [14]:
# Cria uma mascara booleana para os elementos pares
mask = (arr1 % 2 == 0)

In [15]:
arr1[mask]

array([10, 32, 48, 76])

In [16]:
# Alterando um elemento do array
arr1[0] = 100

In [17]:
print(arr1)

[100  21  32  43  48  15  76  57  89]


In [18]:
# Não é possivel incluir um elemento de outro tipo
try:
    arr1[0] = 'Novo elemento'
except:
    print("Operação não permitida!")

Operação não permitida!
